name: SourceHan font ttf

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.git**'
      - '**.md'
      - 'LICENSE'
  workflow_dispatch:
    inputs:
      version:
        description: 'release version'
        required: false
        default: 'latest'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main

      - uses: actions/setup-python@main
        with:
          check-latest: true

      - name: processing
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # 安装 fonttools
          pip install fonttools
          curl -LOJ https://raw.githubusercontent.com/fonttools/fonttools/main/Snippets/otf2ttf.py

          # 思源黑体SC
          curl -Lo SourceHanSansSC.zip https://github.com/adobe-fonts/source-han-sans/releases/latest/download/09_SourceHanSansSC.zip
          # 思源黑体TC
          curl -Lo SourceHanSansTC.zip https://github.com/adobe-fonts/source-han-sans/releases/latest/download/10_SourceHanSansTC.zip
          # 思源宋体SC
          curl -Lo SourceHanSerifSC.zip https://github.com/adobe-fonts/source-han-serif/releases/latest/download/09_SourceHanSerifSC.zip
          # 思源宋体TC
          curl -Lo SourceHanSerifTC.zip https://github.com/adobe-fonts/source-han-serif/releases/latest/download/10_SourceHanSerifTC.zip

          # 解压
          for file in *.zip; do
            unzip -o "$file" "*.otf" -d temp
          done

          # 创建工作路径
          mkdir -p fonts
          find temp -type f -name "*.otf" -exec mv {} fonts/ \;

          # 转换
          for file in fonts/*.otf; do
            python3 otf2ttf.py "$file"
          done
          
          # 打包
          cd fonts || exit 1
          SANS_VERSION="$(curl --silent "https://api.github.com/repos/adobe-fonts/source-han-sans/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')"
          SERIF_VERSION="$(curl --silent "https://api.github.com/repos/adobe-fonts/source-han-serif/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')"
          zip -9 -r -UN=UTF8 ./SourceHanSansSC_TTF_$SANS_VERSION.zip SourceHanSansSC-*.ttf
          zip -9 -r -UN=UTF8 ./SourceHanSansTC_TTF_$SANS_VERSION.zip SourceHanSansTC-*.ttf
          zip -9 -r -UN=UTF8 ./SourceHanSerifSC_TTF_$SERIF_VERSION.zip SourceHanSerifSC-*.ttf
          zip -9 -r -UN=UTF8 ./SourceHanSerifTC_TTF_$SERIF_VERSION.zip SourceHanSerifTC-*.ttf
          cd .. || exit 1

          # delete all releases and their tags
          gh release list | awk -F '\t' '{print $3}' | while read -r line; do gh release delete --yes --cleanup-tag "$line"; done

          # create release
          if [ "${{ inputs.version }}" != "" ]; then
            tag="${{ inputs.version }}"
          else
            tag="$(date +"%Y%m%d")"
          fi
          gh release create "$tag" --generate-notes "fonts/*TTF*.zip"
